package lima

import (
	"fmt"
	"os"
	"text/template"
)

type TemplateConfig struct {
	CPUs         int
	MemoryGiB    int
	DiskGiB      int
	SharedDir    string // host path to ~/.agentvm/shared
	HostIP       string // for registration callback
	RegistryPort int    // registration server port
}

func DefaultTemplateConfig() TemplateConfig {
	home, _ := os.UserHomeDir()
	return TemplateConfig{
		CPUs:         2,
		MemoryGiB:    3,
		DiskGiB:      30,
		SharedDir:    fmt.Sprintf("%s/.agentvm/shared", home),
		HostIP:       "host.lima.internal",
		RegistryPort: 8090,
	}
}

const masterTemplate = `# Lima VM template for agent-master golden image
# Generated by agentvm

vmType: vz
os: Linux
arch: aarch64

images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"

cpus: {{ .CPUs }}
memory: "{{ .MemoryGiB }}GiB"
disk: "{{ .DiskGiB }}GiB"

networks:
  - vzNAT: true

mountType: virtiofs
mounts:
  - location: "{{ .SharedDir }}"
    mountPoint: "/mnt/host-shared"
    writable: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux

      # Wait for network
      for i in $(seq 1 30); do
        if ping -c1 -W2 archive.ubuntu.com >/dev/null 2>&1; then break; fi
        sleep 2
      done

      export DEBIAN_FRONTEND=noninteractive

      # Base packages
      apt-get update
      apt-get install -y \
        ca-certificates curl gnupg lsb-release \
        git jq unzip build-essential \
        apt-transport-https software-properties-common

      # Docker CE
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      usermod -aG docker ${LIMA_CIDATA_USER:-lima}

      # Node.js 22
      curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      apt-get install -y nodejs

      # GitHub CLI
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list
      apt-get update
      apt-get install -y gh

      # Claude Code CLI
      npm install -g @anthropic-ai/claude-code

      # Install agent-harness from shared mount
      if [ -f /mnt/host-shared/bin/agent-harness ]; then
        cp /mnt/host-shared/bin/agent-harness /usr/local/bin/agent-harness
        chmod +x /usr/local/bin/agent-harness
      fi

      # Create config directory (writable by lima user for task injection)
      mkdir -p /etc/agent-config
      chmod 777 /etc/agent-config

      # Configure git identity for the VM user
      VMUSER=$(getent passwd 501 | cut -d: -f1 || echo "lima")
      VMHOME=$(getent passwd 501 | cut -d: -f6 || echo "/home/lima")
      sudo -u "$VMUSER" git config --global user.name "AgentVM"
      sudo -u "$VMUSER" git config --global user.email "agentvm@localhost"

      # Install systemd service for agent-harness (runs as VM user, not root)
      cat > /etc/systemd/system/agent-harness.service <<UNIT
      [Unit]
      Description=Agent Harness Daemon
      After=network-online.target docker.service
      Wants=network-online.target

      [Service]
      Type=simple
      User=$VMUSER
      WorkingDirectory=$VMHOME
      EnvironmentFile=-/etc/agent-config/env
      ExecStart=/usr/local/bin/agent-harness
      Restart=on-failure
      RestartSec=5
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target
      UNIT

      systemctl daemon-reload
      systemctl enable agent-harness.service

  - mode: boot
    script: |
      #!/bin/bash
      set -eu

      # Wait for network
      for i in $(seq 1 30); do
        if ping -c1 -W2 {{ .HostIP }} >/dev/null 2>&1; then break; fi
        sleep 2
      done

      # Refresh harness binary if updated on host
      if [ -f /mnt/host-shared/bin/agent-harness ]; then
        cp /mnt/host-shared/bin/agent-harness /usr/local/bin/agent-harness
        chmod +x /usr/local/bin/agent-harness
      fi

      # Restart harness service if task config exists
      if [ -f /etc/agent-config/task.json ]; then
        systemctl restart agent-harness.service
      fi
`

func RenderTemplate(cfg TemplateConfig, outputPath string) error {
	tmpl, err := template.New("lima").Parse(masterTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, cfg); err != nil {
		return fmt.Errorf("failed to render template: %w", err)
	}
	return nil
}
